[workspace]
resolver = "2"
members = [
    # WSDF
    "crates/wsdf",
    "crates/wsdf-derive",
    "crates/epan-sys",

    # Dissectors
    "crates/valve",
    "crates/minecraft-java",
    "crates/minecraft-bedrock"
]